[package]
name = 'fio'
version = '0.0.9001'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'fio'

[dependencies]
extendr-api = {git = "https://github.com/extendr/extendr", default-features = false, features = ["faer"]}
faer = '0.19.0'
rayon = '1.10.0'